"""
Sensor observation models and abstract interfaces for Edge Robot.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
import time
from typing import List, Tuple, Dict, Any, Optional

from edge_robot.core.enums import ObstacleType


@dataclass
class DetectedObstacleData:
    """Single obstacle observation generated by perception or sensor system."""
    obstacle_id: str
    obstacle_type: ObstacleType
    position: Tuple[float, float]  # World (x, y) coordinates
    distance: float  # Distance from robot in meters
    confidence: float = 1.0
    source: str = "mock_sensor"
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "obstacle_id": self.obstacle_id,
            "obstacle_type": self.obstacle_type.value if isinstance(self.obstacle_type, ObstacleType) else str(self.obstacle_type),
            "position": list(self.position),
            "distance": round(self.distance, 2),
            "confidence": round(self.confidence, 2),
            "source": self.source,
            "timestamp": self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> DetectedObstacleData:
        return cls(
            obstacle_id=data.get("obstacle_id", "obs-0"),
            obstacle_type=ObstacleType(data.get("obstacle_type", ObstacleType.DYNAMIC_OBSTACLE.value)),
            position=tuple(data.get("position", (0.0, 0.0))),
            distance=float(data.get("distance", 0.0)),
            confidence=float(data.get("confidence", 1.0)),
            source=data.get("source", "sensor"),
            timestamp=float(data.get("timestamp", time.time())),
        )


@dataclass
class SensorObservation:
    """Aggregate observation returned by sensor / perception module."""
    obstacles: List[DetectedObstacleData] = field(default_factory=list)
    min_obstacle_distance: float = 999.0
    timestamp: float = field(default_factory=time.time)


class SensorInterface(ABC):
    """Abstract interface for sensor & perception providers."""

    @abstractmethod
    def get_observation(self) -> SensorObservation:
        """Fetch latest sensor observation."""
        pass
